apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: bookstore
data:
  SERVICE_NAME: "auth-service"
  PORT: "3001"
  GRPC_PORT: "50051"
  NODE_ENV: "production"
  LOG_LEVEL: "info"

  # PostgreSQL — RDS
  DB_HOST: "bookstore-postgres.cw8htjuayjec.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_USER: "auth_user"
  DB_NAME: "bookstore_main"
  DB_SCHEMA: "auth"

  # JWT config (no sensible — los secrets van en el Secret)
  JWT_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"

  # Proto dir dentro del contenedor
  PROTO_DIR: "/app/proto"