curl -X POST http://localhost:3004/orders \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNDg3MTBiNy1lYjg3LTQ2MjktODM5MS01MThmMDMxMWIwNjYiLCJlbWFpbCI6InZhbGVudGluYUBib29rc3RvcmUuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzgwMDU3NjQzLCJleHAiOjE3ODAwNTg1NDN9.MVNcvkg3dufl9eibCxpyiPtG3XuZnAkwzE9ODF6pUzg" \
  -d '{
    "shipping_name": "Valentina Benitez",
    "shipping_email": "valentina@bookstore.com",
    "shipping_address": "Carrera 36"
  }'