curl http://localhost:3003/health

-- eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMDAzZGFhMy1iYWFmLTRkYzMtOWJiZC1hYzc0YzJiZWE5N2IiLCJlbWFpbCI6InZhbGVudGluYUBib29rc3RvcmUuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzc5OTQ1OTk1LCJleHAiOjE3Nzk5NDY4OTV9.X0wZil5_DWktAhY4MnBkv0i_li233N1bM7itJEimcL8
-- -- 58917b2f-5cb5-420e-8ab8-15355a9b2a76