apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: bookstore
  labels:
    app: cart-service
spec:
  selector:
    app: cart-service
  type: ClusterIP
  ports:
    - name: http
      port: 3003
      targetPort: 3003
      protocol: TCP
    - name: grpc
      port: 50053
      targetPort: 50053
      protocol: TCP