apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: bookstore
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 578426902456.dkr.ecr.us-east-1.amazonaws.com/bookstore/order-service:latest
          ports:
            - containerPort: 3004
              name: http

          envFrom:
            - configMapRef:
                name: order-service-config

          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookstore-secrets
                  key: ORDER_DB_PASSWORD

          readinessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"

      restartPolicy: Always
      terminationGracePeriodSeconds: 30