apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service-config
  namespace: bookstore
data:
  SERVICE_NAME: "catalog-service"
  PORT: "3002"
  GRPC_PORT: "50052"
  NODE_ENV: "production"
  LOG_LEVEL: "info"

  # PostgreSQL — RDS
  DB_HOST: "bookstore-postgres.cw8htjuayjec.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_USER: "catalog_user"
  DB_NAME: "bookstore_main"
  DB_SCHEMA: "catalog"

  PROTO_DIR: "/app/proto"