apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: bookstore
  labels:
    app: catalog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: 578426902456.dkr.ecr.us-east-1.amazonaws.com/bookstore/catalog-service:latest
          ports:
            - containerPort: 3002
              name: http
            - containerPort: 50052
              name: grpc

          envFrom:
            - configMapRef:
                name: catalog-service-config

          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookstore-secrets
                  key: CATALOG_DB_PASSWORD

          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 40
            periodSeconds: 20
            failureThreshold: 3

          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "500m"

      restartPolicy: Always
      terminationGracePeriodSeconds: 30