apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: bookstore
  labels:
    app: catalog-service
spec:
  selector:
    app: catalog-service
  type: ClusterIP
  ports:
    - name: http
      port: 3002
      targetPort: 3002
      protocol: TCP
    - name: grpc
      port: 50052
      targetPort: 50052
      protocol: TCP