# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\x12\x07\x63\x61talog\"!\n\x0eGetBookRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\"\x9e\x01\n\x0fGetBookResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x0f\n\x07\x62ook_id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x04 \x01(\t\x12\x0c\n\x04isbn\x18\x05 \x01(\t\x12\r\n\x05price\x18\x06 \x01(\x01\x12\r\n\x05stock\x18\x07 \x01(\x05\x12\x11\n\tcover_url\x18\x08 \x01(\t\x12\r\n\x05\x65rror\x18\t \x01(\t\"6\n\x11\x43heckStockRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"^\n\x12\x43heckStockResponse\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\x15\n\rcurrent_stock\x18\x02 \x01(\x05\x12\x0f\n\x07\x62ook_id\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"I\n\x12\x44\x65\x64uctStockRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12!\n\x05items\x18\x02 \x03(\x0b\x32\x12.catalog.StockItem\".\n\tStockItem\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"5\n\x13\x44\x65\x64uctStockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"J\n\x13RestoreStockRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12!\n\x05items\x18\x02 \x03(\x0b\x32\x12.catalog.StockItem\"6\n\x14RestoreStockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xac\x02\n\x0e\x43\x61talogService\x12<\n\x07GetBook\x12\x17.catalog.GetBookRequest\x1a\x18.catalog.GetBookResponse\x12\x45\n\nCheckStock\x12\x1a.catalog.CheckStockRequest\x1a\x1b.catalog.CheckStockResponse\x12H\n\x0b\x44\x65\x64uctStock\x12\x1b.catalog.DeductStockRequest\x1a\x1c.catalog.DeductStockResponse\x12K\n\x0cRestoreStock\x12\x1c.catalog.RestoreStockRequest\x1a\x1d.catalog.RestoreStockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBOOKREQUEST']._serialized_start=26
  _globals['_GETBOOKREQUEST']._serialized_end=59
  _globals['_GETBOOKRESPONSE']._serialized_start=62
  _globals['_GETBOOKRESPONSE']._serialized_end=220
  _globals['_CHECKSTOCKREQUEST']._serialized_start=222
  _globals['_CHECKSTOCKREQUEST']._serialized_end=276
  _globals['_CHECKSTOCKRESPONSE']._serialized_start=278
  _globals['_CHECKSTOCKRESPONSE']._serialized_end=372
  _globals['_DEDUCTSTOCKREQUEST']._serialized_start=374
  _globals['_DEDUCTSTOCKREQUEST']._serialized_end=447
  _globals['_STOCKITEM']._serialized_start=449
  _globals['_STOCKITEM']._serialized_end=495
  _globals['_DEDUCTSTOCKRESPONSE']._serialized_start=497
  _globals['_DEDUCTSTOCKRESPONSE']._serialized_end=550
  _globals['_RESTORESTOCKREQUEST']._serialized_start=552
  _globals['_RESTORESTOCKREQUEST']._serialized_end=626
  _globals['_RESTORESTOCKRESPONSE']._serialized_start=628
  _globals['_RESTORESTOCKRESPONSE']._serialized_end=682
  _globals['_CATALOGSERVICE']._serialized_start=685
  _globals['_CATALOGSERVICE']._serialized_end=985
# @@protoc_insertion_point(module_scope)
