# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import catalog_pb2 as catalog__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in catalog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class CatalogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBook = channel.unary_unary(
                '/catalog.CatalogService/GetBook',
                request_serializer=catalog__pb2.GetBookRequest.SerializeToString,
                response_deserializer=catalog__pb2.GetBookResponse.FromString,
                _registered_method=True)
        self.CheckStock = channel.unary_unary(
                '/catalog.CatalogService/CheckStock',
                request_serializer=catalog__pb2.CheckStockRequest.SerializeToString,
                response_deserializer=catalog__pb2.CheckStockResponse.FromString,
                _registered_method=True)
        self.DeductStock = channel.unary_unary(
                '/catalog.CatalogService/DeductStock',
                request_serializer=catalog__pb2.DeductStockRequest.SerializeToString,
                response_deserializer=catalog__pb2.DeductStockResponse.FromString,
                _registered_method=True)
        self.RestoreStock = channel.unary_unary(
                '/catalog.CatalogService/RestoreStock',
                request_serializer=catalog__pb2.RestoreStockRequest.SerializeToString,
                response_deserializer=catalog__pb2.RestoreStockResponse.FromString,
                _registered_method=True)


class CatalogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBook(self, request, context):
        """Obtiene los datos de un libro por su ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckStock(self, request, context):
        """Verifica si hay stock suficiente para una cantidad dada.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeductStock(self, request, context):
        """Descuenta unidades del stock al confirmar una orden.
        Solo debe llamarse desde Order Service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreStock(self, request, context):
        """Restaura stock si un pago falla (compensación).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=catalog__pb2.GetBookRequest.FromString,
                    response_serializer=catalog__pb2.GetBookResponse.SerializeToString,
            ),
            'CheckStock': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStock,
                    request_deserializer=catalog__pb2.CheckStockRequest.FromString,
                    response_serializer=catalog__pb2.CheckStockResponse.SerializeToString,
            ),
            'DeductStock': grpc.unary_unary_rpc_method_handler(
                    servicer.DeductStock,
                    request_deserializer=catalog__pb2.DeductStockRequest.FromString,
                    response_serializer=catalog__pb2.DeductStockResponse.SerializeToString,
            ),
            'RestoreStock': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreStock,
                    request_deserializer=catalog__pb2.RestoreStockRequest.FromString,
                    response_serializer=catalog__pb2.RestoreStockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'catalog.CatalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('catalog.CatalogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CatalogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.CatalogService/GetBook',
            catalog__pb2.GetBookRequest.SerializeToString,
            catalog__pb2.GetBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.CatalogService/CheckStock',
            catalog__pb2.CheckStockRequest.SerializeToString,
            catalog__pb2.CheckStockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeductStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.CatalogService/DeductStock',
            catalog__pb2.DeductStockRequest.SerializeToString,
            catalog__pb2.DeductStockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.CatalogService/RestoreStock',
            catalog__pb2.RestoreStockRequest.SerializeToString,
            catalog__pb2.RestoreStockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
